[package]
name = "protocol-fixtures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "protocol-fixtures"
path = "main.rs"

[dependencies]
rclweb = { path = "../../rclweb" }
serde_json.workspace = true
sha2.workspace = true
