/* automatically generated by rust-bindgen 0.72.1 */

//! Vendored bindgen output for the serialized-only rcl surface (J-FT).
//! Regenerate with scripts/generate-rcl-bindings.sh; do not edit by hand.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(unsafe_code, dead_code, clippy::all, missing_docs)]

pub const RMW_RET_OK: u32 = 0;
pub const RMW_RET_ERROR: u32 = 1;
pub const RMW_RET_TIMEOUT: u32 = 2;
pub const RMW_RET_UNSUPPORTED: u32 = 3;
pub const RMW_RET_BAD_ALLOC: u32 = 10;
pub const RMW_RET_INVALID_ARGUMENT: u32 = 11;
pub const RMW_RET_INCORRECT_RMW_IMPLEMENTATION: u32 = 12;
pub const RMW_RET_NODE_NAME_NON_EXISTENT: u32 = 203;
pub const RCL_RET_OK: u32 = 0;
pub const RCL_RET_ERROR: u32 = 1;
pub const RCL_RET_TIMEOUT: u32 = 2;
pub const RCL_RET_BAD_ALLOC: u32 = 10;
pub const RCL_RET_INVALID_ARGUMENT: u32 = 11;
pub const RCL_RET_UNSUPPORTED: u32 = 3;
pub const RCL_RET_ALREADY_INIT: u32 = 100;
pub const RCL_RET_NOT_INIT: u32 = 101;
pub const RCL_RET_MISMATCHED_RMW_ID: u32 = 102;
pub const RCL_RET_TOPIC_NAME_INVALID: u32 = 103;
pub const RCL_RET_SERVICE_NAME_INVALID: u32 = 104;
pub const RCL_RET_UNKNOWN_SUBSTITUTION: u32 = 105;
pub const RCL_RET_ALREADY_SHUTDOWN: u32 = 106;
pub const RCL_RET_NOT_FOUND: u32 = 107;
pub const RCL_RET_NODE_INVALID: u32 = 200;
pub const RCL_RET_NODE_INVALID_NAME: u32 = 201;
pub const RCL_RET_NODE_INVALID_NAMESPACE: u32 = 202;
pub const RCL_RET_NODE_NAME_NON_EXISTENT: u32 = 203;
pub const RCL_RET_PUBLISHER_INVALID: u32 = 300;
pub const RCL_RET_SUBSCRIPTION_INVALID: u32 = 400;
pub const RCL_RET_SUBSCRIPTION_TAKE_FAILED: u32 = 401;
pub const RCL_RET_CLIENT_INVALID: u32 = 500;
pub const RCL_RET_CLIENT_TAKE_FAILED: u32 = 501;
pub const RCL_RET_SERVICE_INVALID: u32 = 600;
pub const RCL_RET_SERVICE_TAKE_FAILED: u32 = 601;
pub const RCL_RET_TIMER_INVALID: u32 = 800;
pub const RCL_RET_TIMER_CANCELED: u32 = 801;
pub const RCL_RET_WAIT_SET_INVALID: u32 = 900;
pub const RCL_RET_WAIT_SET_EMPTY: u32 = 901;
pub const RCL_RET_WAIT_SET_FULL: u32 = 902;
pub const RCL_RET_INVALID_REMAP_RULE: u32 = 1001;
pub const RCL_RET_WRONG_LEXEME: u32 = 1002;
pub const RCL_RET_INVALID_ROS_ARGS: u32 = 1003;
pub const RCL_RET_INVALID_PARAM_RULE: u32 = 1010;
pub const RCL_RET_INVALID_LOG_LEVEL_RULE: u32 = 1020;
pub const RCL_RET_EVENT_INVALID: u32 = 2000;
pub const RCL_RET_EVENT_TAKE_FAILED: u32 = 2001;
pub const RCL_RET_LIFECYCLE_STATE_REGISTERED: u32 = 3000;
pub const RCL_RET_LIFECYCLE_STATE_NOT_REGISTERED: u32 = 3001;
pub const RCL_ACTION_RET_NOT_TERMINATED_YET: u32 = 4001;
pub const RCL_RET_ACTION_NAME_INVALID: u32 = 2000;
pub const RCL_RET_ACTION_GOAL_ACCEPTED: u32 = 2100;
pub const RCL_RET_ACTION_GOAL_REJECTED: u32 = 2101;
pub const RCL_RET_ACTION_CLIENT_INVALID: u32 = 2102;
pub const RCL_RET_ACTION_CLIENT_TAKE_FAILED: u32 = 2103;
pub const RCL_RET_ACTION_SERVER_INVALID: u32 = 2200;
pub const RCL_RET_ACTION_SERVER_TAKE_FAILED: u32 = 2201;
pub const RCL_RET_ACTION_GOAL_HANDLE_INVALID: u32 = 2300;
pub const RCL_RET_ACTION_GOAL_EVENT_INVALID: u32 = 2301;
pub type rcutils_ret_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcutils_allocator_s {
    pub allocate: ::std::option::Option<
        unsafe extern "C" fn(
            size: usize,
            state: *mut ::std::os::raw::c_void,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub deallocate: ::std::option::Option<
        unsafe extern "C" fn(
            pointer: *mut ::std::os::raw::c_void,
            state: *mut ::std::os::raw::c_void,
        ),
    >,
    pub reallocate: ::std::option::Option<
        unsafe extern "C" fn(
            pointer: *mut ::std::os::raw::c_void,
            size: usize,
            state: *mut ::std::os::raw::c_void,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub zero_allocate: ::std::option::Option<
        unsafe extern "C" fn(
            number_of_elements: usize,
            size_of_element: usize,
            state: *mut ::std::os::raw::c_void,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub state: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcutils_allocator_s"][::std::mem::size_of::<rcutils_allocator_s>() - 40usize];
    ["Alignment of rcutils_allocator_s"][::std::mem::align_of::<rcutils_allocator_s>() - 8usize];
    ["Offset of field: rcutils_allocator_s::allocate"]
        [::std::mem::offset_of!(rcutils_allocator_s, allocate) - 0usize];
    ["Offset of field: rcutils_allocator_s::deallocate"]
        [::std::mem::offset_of!(rcutils_allocator_s, deallocate) - 8usize];
    ["Offset of field: rcutils_allocator_s::reallocate"]
        [::std::mem::offset_of!(rcutils_allocator_s, reallocate) - 16usize];
    ["Offset of field: rcutils_allocator_s::zero_allocate"]
        [::std::mem::offset_of!(rcutils_allocator_s, zero_allocate) - 24usize];
    ["Offset of field: rcutils_allocator_s::state"]
        [::std::mem::offset_of!(rcutils_allocator_s, state) - 32usize];
};
pub type rcutils_allocator_t = rcutils_allocator_s;
unsafe extern "C" {
    pub fn rcutils_get_default_allocator() -> rcutils_allocator_t;
}
pub type rcl_allocator_t = rcutils_allocator_t;
pub type rmw_ret_t = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcutils_error_string_s {
    pub str_: [::std::os::raw::c_char; 1024usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcutils_error_string_s"][::std::mem::size_of::<rcutils_error_string_s>() - 1024usize];
    ["Alignment of rcutils_error_string_s"]
        [::std::mem::align_of::<rcutils_error_string_s>() - 1usize];
    ["Offset of field: rcutils_error_string_s::str_"]
        [::std::mem::offset_of!(rcutils_error_string_s, str_) - 0usize];
};
pub type rcutils_error_string_t = rcutils_error_string_s;
unsafe extern "C" {
    pub fn rcutils_get_error_string() -> rcutils_error_string_t;
}
unsafe extern "C" {
    pub fn rcutils_reset_error();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcutils_string_array_s {
    pub size: usize,
    pub data: *mut *mut ::std::os::raw::c_char,
    pub allocator: rcutils_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcutils_string_array_s"][::std::mem::size_of::<rcutils_string_array_s>() - 56usize];
    ["Alignment of rcutils_string_array_s"]
        [::std::mem::align_of::<rcutils_string_array_s>() - 8usize];
    ["Offset of field: rcutils_string_array_s::size"]
        [::std::mem::offset_of!(rcutils_string_array_s, size) - 0usize];
    ["Offset of field: rcutils_string_array_s::data"]
        [::std::mem::offset_of!(rcutils_string_array_s, data) - 8usize];
    ["Offset of field: rcutils_string_array_s::allocator"]
        [::std::mem::offset_of!(rcutils_string_array_s, allocator) - 16usize];
};
pub type rcutils_string_array_t = rcutils_string_array_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcutils_uint8_array_s {
    pub buffer: *mut u8,
    pub buffer_length: usize,
    pub buffer_capacity: usize,
    pub allocator: rcutils_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcutils_uint8_array_s"][::std::mem::size_of::<rcutils_uint8_array_s>() - 64usize];
    ["Alignment of rcutils_uint8_array_s"]
        [::std::mem::align_of::<rcutils_uint8_array_s>() - 8usize];
    ["Offset of field: rcutils_uint8_array_s::buffer"]
        [::std::mem::offset_of!(rcutils_uint8_array_s, buffer) - 0usize];
    ["Offset of field: rcutils_uint8_array_s::buffer_length"]
        [::std::mem::offset_of!(rcutils_uint8_array_s, buffer_length) - 8usize];
    ["Offset of field: rcutils_uint8_array_s::buffer_capacity"]
        [::std::mem::offset_of!(rcutils_uint8_array_s, buffer_capacity) - 16usize];
    ["Offset of field: rcutils_uint8_array_s::allocator"]
        [::std::mem::offset_of!(rcutils_uint8_array_s, allocator) - 24usize];
};
pub type rcutils_uint8_array_t = rcutils_uint8_array_s;
unsafe extern "C" {
    pub fn rcutils_get_zero_initialized_uint8_array() -> rcutils_uint8_array_t;
}
unsafe extern "C" {
    pub fn rcutils_uint8_array_init(
        uint8_array: *mut rcutils_uint8_array_t,
        buffer_capacity: usize,
        allocator: *const rcutils_allocator_t,
    ) -> rcutils_ret_t;
}
unsafe extern "C" {
    pub fn rcutils_uint8_array_fini(uint8_array: *mut rcutils_uint8_array_t) -> rcutils_ret_t;
}
pub type rcutils_time_point_value_t = i64;
pub type rmw_serialized_message_t = rcutils_uint8_array_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_subscription_content_filter_options_s {
    pub filter_expression: *mut ::std::os::raw::c_char,
    pub expression_parameters: rcutils_string_array_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_subscription_content_filter_options_s"]
        [::std::mem::size_of::<rmw_subscription_content_filter_options_s>() - 64usize];
    ["Alignment of rmw_subscription_content_filter_options_s"]
        [::std::mem::align_of::<rmw_subscription_content_filter_options_s>() - 8usize];
    ["Offset of field: rmw_subscription_content_filter_options_s::filter_expression"][::std::mem::offset_of!(
        rmw_subscription_content_filter_options_s,
        filter_expression
    ) - 0usize];
    ["Offset of field: rmw_subscription_content_filter_options_s::expression_parameters"][::std::mem::offset_of!(
        rmw_subscription_content_filter_options_s,
        expression_parameters
    )
        - 8usize];
};
pub type rmw_subscription_content_filter_options_t = rmw_subscription_content_filter_options_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_time_s {
    pub sec: u64,
    pub nsec: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_time_s"][::std::mem::size_of::<rmw_time_s>() - 16usize];
    ["Alignment of rmw_time_s"][::std::mem::align_of::<rmw_time_s>() - 8usize];
    ["Offset of field: rmw_time_s::sec"][::std::mem::offset_of!(rmw_time_s, sec) - 0usize];
    ["Offset of field: rmw_time_s::nsec"][::std::mem::offset_of!(rmw_time_s, nsec) - 8usize];
};
pub type rmw_time_point_value_t = rcutils_time_point_value_t;
pub const RMW_UNIQUE_NETWORK_FLOW_ENDPOINTS_NOT_REQUIRED:
    rmw_unique_network_flow_endpoints_requirement_e = 0;
pub const RMW_UNIQUE_NETWORK_FLOW_ENDPOINTS_STRICTLY_REQUIRED:
    rmw_unique_network_flow_endpoints_requirement_e = 1;
pub const RMW_UNIQUE_NETWORK_FLOW_ENDPOINTS_OPTIONALLY_REQUIRED:
    rmw_unique_network_flow_endpoints_requirement_e = 2;
pub const RMW_UNIQUE_NETWORK_FLOW_ENDPOINTS_SYSTEM_DEFAULT:
    rmw_unique_network_flow_endpoints_requirement_e = 3;
pub type rmw_unique_network_flow_endpoints_requirement_e = ::std::os::raw::c_uint;
pub use self::rmw_unique_network_flow_endpoints_requirement_e as rmw_unique_network_flow_endpoints_requirement_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_publisher_options_s {
    pub rmw_specific_publisher_payload: *mut ::std::os::raw::c_void,
    pub require_unique_network_flow_endpoints: rmw_unique_network_flow_endpoints_requirement_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_publisher_options_s"][::std::mem::size_of::<rmw_publisher_options_s>() - 16usize];
    ["Alignment of rmw_publisher_options_s"]
        [::std::mem::align_of::<rmw_publisher_options_s>() - 8usize];
    ["Offset of field: rmw_publisher_options_s::rmw_specific_publisher_payload"]
        [::std::mem::offset_of!(rmw_publisher_options_s, rmw_specific_publisher_payload) - 0usize];
    ["Offset of field: rmw_publisher_options_s::require_unique_network_flow_endpoints"][::std::mem::offset_of!(
        rmw_publisher_options_s,
        require_unique_network_flow_endpoints
    ) - 8usize];
};
pub type rmw_publisher_options_t = rmw_publisher_options_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_subscription_options_s {
    pub rmw_specific_subscription_payload: *mut ::std::os::raw::c_void,
    pub ignore_local_publications: bool,
    pub require_unique_network_flow_endpoints: rmw_unique_network_flow_endpoints_requirement_t,
    pub content_filter_options: *mut rmw_subscription_content_filter_options_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_subscription_options_s"]
        [::std::mem::size_of::<rmw_subscription_options_s>() - 24usize];
    ["Alignment of rmw_subscription_options_s"]
        [::std::mem::align_of::<rmw_subscription_options_s>() - 8usize];
    ["Offset of field: rmw_subscription_options_s::rmw_specific_subscription_payload"][::std::mem::offset_of!(
        rmw_subscription_options_s,
        rmw_specific_subscription_payload
    ) - 0usize];
    ["Offset of field: rmw_subscription_options_s::ignore_local_publications"]
        [::std::mem::offset_of!(rmw_subscription_options_s, ignore_local_publications) - 8usize];
    ["Offset of field: rmw_subscription_options_s::require_unique_network_flow_endpoints"][::std::mem::offset_of!(
        rmw_subscription_options_s,
        require_unique_network_flow_endpoints
    )
        - 12usize];
    ["Offset of field: rmw_subscription_options_s::content_filter_options"]
        [::std::mem::offset_of!(rmw_subscription_options_s, content_filter_options) - 16usize];
};
pub type rmw_subscription_options_t = rmw_subscription_options_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_publisher_allocation_s {
    pub implementation_identifier: *const ::std::os::raw::c_char,
    pub data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_publisher_allocation_s"]
        [::std::mem::size_of::<rmw_publisher_allocation_s>() - 16usize];
    ["Alignment of rmw_publisher_allocation_s"]
        [::std::mem::align_of::<rmw_publisher_allocation_s>() - 8usize];
    ["Offset of field: rmw_publisher_allocation_s::implementation_identifier"]
        [::std::mem::offset_of!(rmw_publisher_allocation_s, implementation_identifier) - 0usize];
    ["Offset of field: rmw_publisher_allocation_s::data"]
        [::std::mem::offset_of!(rmw_publisher_allocation_s, data) - 8usize];
};
pub type rmw_publisher_allocation_t = rmw_publisher_allocation_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_subscription_allocation_s {
    pub implementation_identifier: *const ::std::os::raw::c_char,
    pub data: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_subscription_allocation_s"]
        [::std::mem::size_of::<rmw_subscription_allocation_s>() - 16usize];
    ["Alignment of rmw_subscription_allocation_s"]
        [::std::mem::align_of::<rmw_subscription_allocation_s>() - 8usize];
    ["Offset of field: rmw_subscription_allocation_s::implementation_identifier"]
        [::std::mem::offset_of!(rmw_subscription_allocation_s, implementation_identifier) - 0usize];
    ["Offset of field: rmw_subscription_allocation_s::data"]
        [::std::mem::offset_of!(rmw_subscription_allocation_s, data) - 8usize];
};
pub type rmw_subscription_allocation_t = rmw_subscription_allocation_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_request_id_s {
    pub writer_guid: [u8; 16usize],
    pub sequence_number: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_request_id_s"][::std::mem::size_of::<rmw_request_id_s>() - 24usize];
    ["Alignment of rmw_request_id_s"][::std::mem::align_of::<rmw_request_id_s>() - 8usize];
    ["Offset of field: rmw_request_id_s::writer_guid"]
        [::std::mem::offset_of!(rmw_request_id_s, writer_guid) - 0usize];
    ["Offset of field: rmw_request_id_s::sequence_number"]
        [::std::mem::offset_of!(rmw_request_id_s, sequence_number) - 16usize];
};
pub type rmw_request_id_t = rmw_request_id_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_service_info_s {
    pub source_timestamp: rmw_time_point_value_t,
    pub received_timestamp: rmw_time_point_value_t,
    pub request_id: rmw_request_id_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_service_info_s"][::std::mem::size_of::<rmw_service_info_s>() - 40usize];
    ["Alignment of rmw_service_info_s"][::std::mem::align_of::<rmw_service_info_s>() - 8usize];
    ["Offset of field: rmw_service_info_s::source_timestamp"]
        [::std::mem::offset_of!(rmw_service_info_s, source_timestamp) - 0usize];
    ["Offset of field: rmw_service_info_s::received_timestamp"]
        [::std::mem::offset_of!(rmw_service_info_s, received_timestamp) - 8usize];
    ["Offset of field: rmw_service_info_s::request_id"]
        [::std::mem::offset_of!(rmw_service_info_s, request_id) - 16usize];
};
pub type rmw_service_info_t = rmw_service_info_s;
pub const RMW_QOS_POLICY_RELIABILITY_SYSTEM_DEFAULT: rmw_qos_reliability_policy_e = 0;
pub const RMW_QOS_POLICY_RELIABILITY_RELIABLE: rmw_qos_reliability_policy_e = 1;
pub const RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT: rmw_qos_reliability_policy_e = 2;
pub const RMW_QOS_POLICY_RELIABILITY_UNKNOWN: rmw_qos_reliability_policy_e = 3;
pub const RMW_QOS_POLICY_RELIABILITY_BEST_AVAILABLE: rmw_qos_reliability_policy_e = 4;
pub type rmw_qos_reliability_policy_e = ::std::os::raw::c_uint;
pub const RMW_QOS_POLICY_HISTORY_SYSTEM_DEFAULT: rmw_qos_history_policy_e = 0;
pub const RMW_QOS_POLICY_HISTORY_KEEP_LAST: rmw_qos_history_policy_e = 1;
pub const RMW_QOS_POLICY_HISTORY_KEEP_ALL: rmw_qos_history_policy_e = 2;
pub const RMW_QOS_POLICY_HISTORY_UNKNOWN: rmw_qos_history_policy_e = 3;
pub type rmw_qos_history_policy_e = ::std::os::raw::c_uint;
pub const RMW_QOS_POLICY_DURABILITY_SYSTEM_DEFAULT: rmw_qos_durability_policy_e = 0;
pub const RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL: rmw_qos_durability_policy_e = 1;
pub const RMW_QOS_POLICY_DURABILITY_VOLATILE: rmw_qos_durability_policy_e = 2;
pub const RMW_QOS_POLICY_DURABILITY_UNKNOWN: rmw_qos_durability_policy_e = 3;
pub const RMW_QOS_POLICY_DURABILITY_BEST_AVAILABLE: rmw_qos_durability_policy_e = 4;
pub type rmw_qos_durability_policy_e = ::std::os::raw::c_uint;
pub const RMW_QOS_POLICY_LIVELINESS_SYSTEM_DEFAULT: rmw_qos_liveliness_policy_e = 0;
pub const RMW_QOS_POLICY_LIVELINESS_AUTOMATIC: rmw_qos_liveliness_policy_e = 1;
pub const RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_NODE: rmw_qos_liveliness_policy_e = 2;
pub const RMW_QOS_POLICY_LIVELINESS_MANUAL_BY_TOPIC: rmw_qos_liveliness_policy_e = 3;
pub const RMW_QOS_POLICY_LIVELINESS_UNKNOWN: rmw_qos_liveliness_policy_e = 4;
pub const RMW_QOS_POLICY_LIVELINESS_BEST_AVAILABLE: rmw_qos_liveliness_policy_e = 5;
pub type rmw_qos_liveliness_policy_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_qos_profile_s {
    pub history: rmw_qos_history_policy_e,
    pub depth: usize,
    pub reliability: rmw_qos_reliability_policy_e,
    pub durability: rmw_qos_durability_policy_e,
    pub deadline: rmw_time_s,
    pub lifespan: rmw_time_s,
    pub liveliness: rmw_qos_liveliness_policy_e,
    pub liveliness_lease_duration: rmw_time_s,
    pub avoid_ros_namespace_conventions: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_qos_profile_s"][::std::mem::size_of::<rmw_qos_profile_s>() - 88usize];
    ["Alignment of rmw_qos_profile_s"][::std::mem::align_of::<rmw_qos_profile_s>() - 8usize];
    ["Offset of field: rmw_qos_profile_s::history"]
        [::std::mem::offset_of!(rmw_qos_profile_s, history) - 0usize];
    ["Offset of field: rmw_qos_profile_s::depth"]
        [::std::mem::offset_of!(rmw_qos_profile_s, depth) - 8usize];
    ["Offset of field: rmw_qos_profile_s::reliability"]
        [::std::mem::offset_of!(rmw_qos_profile_s, reliability) - 16usize];
    ["Offset of field: rmw_qos_profile_s::durability"]
        [::std::mem::offset_of!(rmw_qos_profile_s, durability) - 20usize];
    ["Offset of field: rmw_qos_profile_s::deadline"]
        [::std::mem::offset_of!(rmw_qos_profile_s, deadline) - 24usize];
    ["Offset of field: rmw_qos_profile_s::lifespan"]
        [::std::mem::offset_of!(rmw_qos_profile_s, lifespan) - 40usize];
    ["Offset of field: rmw_qos_profile_s::liveliness"]
        [::std::mem::offset_of!(rmw_qos_profile_s, liveliness) - 56usize];
    ["Offset of field: rmw_qos_profile_s::liveliness_lease_duration"]
        [::std::mem::offset_of!(rmw_qos_profile_s, liveliness_lease_duration) - 64usize];
    ["Offset of field: rmw_qos_profile_s::avoid_ros_namespace_conventions"]
        [::std::mem::offset_of!(rmw_qos_profile_s, avoid_ros_namespace_conventions) - 80usize];
};
pub type rmw_qos_profile_t = rmw_qos_profile_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_gid_s {
    pub implementation_identifier: *const ::std::os::raw::c_char,
    pub data: [u8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_gid_s"][::std::mem::size_of::<rmw_gid_s>() - 24usize];
    ["Alignment of rmw_gid_s"][::std::mem::align_of::<rmw_gid_s>() - 8usize];
    ["Offset of field: rmw_gid_s::implementation_identifier"]
        [::std::mem::offset_of!(rmw_gid_s, implementation_identifier) - 0usize];
    ["Offset of field: rmw_gid_s::data"][::std::mem::offset_of!(rmw_gid_s, data) - 8usize];
};
pub type rmw_gid_t = rmw_gid_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_message_info_s {
    pub source_timestamp: rmw_time_point_value_t,
    pub received_timestamp: rmw_time_point_value_t,
    pub publication_sequence_number: u64,
    pub reception_sequence_number: u64,
    pub publisher_gid: rmw_gid_t,
    pub from_intra_process: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_message_info_s"][::std::mem::size_of::<rmw_message_info_s>() - 64usize];
    ["Alignment of rmw_message_info_s"][::std::mem::align_of::<rmw_message_info_s>() - 8usize];
    ["Offset of field: rmw_message_info_s::source_timestamp"]
        [::std::mem::offset_of!(rmw_message_info_s, source_timestamp) - 0usize];
    ["Offset of field: rmw_message_info_s::received_timestamp"]
        [::std::mem::offset_of!(rmw_message_info_s, received_timestamp) - 8usize];
    ["Offset of field: rmw_message_info_s::publication_sequence_number"]
        [::std::mem::offset_of!(rmw_message_info_s, publication_sequence_number) - 16usize];
    ["Offset of field: rmw_message_info_s::reception_sequence_number"]
        [::std::mem::offset_of!(rmw_message_info_s, reception_sequence_number) - 24usize];
    ["Offset of field: rmw_message_info_s::publisher_gid"]
        [::std::mem::offset_of!(rmw_message_info_s, publisher_gid) - 32usize];
    ["Offset of field: rmw_message_info_s::from_intra_process"]
        [::std::mem::offset_of!(rmw_message_info_s, from_intra_process) - 56usize];
};
pub type rmw_message_info_t = rmw_message_info_s;
pub type rcl_ret_t = rmw_ret_t;
pub type rcl_serialized_message_t = rmw_serialized_message_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_arguments_impl_s {
    _unused: [u8; 0],
}
pub type rcl_arguments_impl_t = rcl_arguments_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_arguments_s {
    pub impl_: *mut rcl_arguments_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_arguments_s"][::std::mem::size_of::<rcl_arguments_s>() - 8usize];
    ["Alignment of rcl_arguments_s"][::std::mem::align_of::<rcl_arguments_s>() - 8usize];
    ["Offset of field: rcl_arguments_s::impl_"]
        [::std::mem::offset_of!(rcl_arguments_s, impl_) - 0usize];
};
pub type rcl_arguments_t = rcl_arguments_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_init_options_impl_s {
    _unused: [u8; 0],
}
pub type rcl_init_options_impl_t = rcl_init_options_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_init_options_s {
    pub impl_: *mut rcl_init_options_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_init_options_s"][::std::mem::size_of::<rcl_init_options_s>() - 8usize];
    ["Alignment of rcl_init_options_s"][::std::mem::align_of::<rcl_init_options_s>() - 8usize];
    ["Offset of field: rcl_init_options_s::impl_"]
        [::std::mem::offset_of!(rcl_init_options_s, impl_) - 0usize];
};
pub type rcl_init_options_t = rcl_init_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_init_options() -> rcl_init_options_t;
}
unsafe extern "C" {
    pub fn rcl_init_options_init(
        init_options: *mut rcl_init_options_t,
        allocator: rcl_allocator_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_init_options_fini(init_options: *mut rcl_init_options_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_init_options_set_domain_id(
        init_options: *mut rcl_init_options_t,
        domain_id: usize,
    ) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_context_impl_s {
    _unused: [u8; 0],
}
pub type rcl_context_impl_t = rcl_context_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_context_s {
    pub global_arguments: rcl_arguments_t,
    pub impl_: *mut rcl_context_impl_t,
    pub instance_id_storage: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_context_s"][::std::mem::size_of::<rcl_context_s>() - 24usize];
    ["Alignment of rcl_context_s"][::std::mem::align_of::<rcl_context_s>() - 8usize];
    ["Offset of field: rcl_context_s::global_arguments"]
        [::std::mem::offset_of!(rcl_context_s, global_arguments) - 0usize];
    ["Offset of field: rcl_context_s::impl_"]
        [::std::mem::offset_of!(rcl_context_s, impl_) - 8usize];
    ["Offset of field: rcl_context_s::instance_id_storage"]
        [::std::mem::offset_of!(rcl_context_s, instance_id_storage) - 16usize];
};
pub type rcl_context_t = rcl_context_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_context() -> rcl_context_t;
}
unsafe extern "C" {
    pub fn rcl_context_fini(context: *mut rcl_context_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_init(
        argc: ::std::os::raw::c_int,
        argv: *const *const ::std::os::raw::c_char,
        options: *const rcl_init_options_t,
        context: *mut rcl_context_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_shutdown(context: *mut rcl_context_t) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_guard_condition_impl_s {
    _unused: [u8; 0],
}
pub type rcl_guard_condition_impl_t = rcl_guard_condition_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_guard_condition_s {
    pub context: *mut rcl_context_t,
    pub impl_: *mut rcl_guard_condition_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_guard_condition_s"][::std::mem::size_of::<rcl_guard_condition_s>() - 16usize];
    ["Alignment of rcl_guard_condition_s"]
        [::std::mem::align_of::<rcl_guard_condition_s>() - 8usize];
    ["Offset of field: rcl_guard_condition_s::context"]
        [::std::mem::offset_of!(rcl_guard_condition_s, context) - 0usize];
    ["Offset of field: rcl_guard_condition_s::impl_"]
        [::std::mem::offset_of!(rcl_guard_condition_s, impl_) - 8usize];
};
pub type rcl_guard_condition_t = rcl_guard_condition_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_guard_condition_options_s {
    pub allocator: rcl_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_guard_condition_options_s"]
        [::std::mem::size_of::<rcl_guard_condition_options_s>() - 40usize];
    ["Alignment of rcl_guard_condition_options_s"]
        [::std::mem::align_of::<rcl_guard_condition_options_s>() - 8usize];
    ["Offset of field: rcl_guard_condition_options_s::allocator"]
        [::std::mem::offset_of!(rcl_guard_condition_options_s, allocator) - 0usize];
};
pub type rcl_guard_condition_options_t = rcl_guard_condition_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_guard_condition() -> rcl_guard_condition_t;
}
unsafe extern "C" {
    pub fn rcl_guard_condition_init(
        guard_condition: *mut rcl_guard_condition_t,
        context: *mut rcl_context_t,
        options: rcl_guard_condition_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_guard_condition_fini(guard_condition: *mut rcl_guard_condition_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_guard_condition_get_default_options() -> rcl_guard_condition_options_t;
}
unsafe extern "C" {
    pub fn rcl_trigger_guard_condition(guard_condition: *mut rcl_guard_condition_t) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_node_options_s {
    pub allocator: rcl_allocator_t,
    pub use_global_arguments: bool,
    pub arguments: rcl_arguments_t,
    pub enable_rosout: bool,
    pub rosout_qos: rmw_qos_profile_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_node_options_s"][::std::mem::size_of::<rcl_node_options_s>() - 152usize];
    ["Alignment of rcl_node_options_s"][::std::mem::align_of::<rcl_node_options_s>() - 8usize];
    ["Offset of field: rcl_node_options_s::allocator"]
        [::std::mem::offset_of!(rcl_node_options_s, allocator) - 0usize];
    ["Offset of field: rcl_node_options_s::use_global_arguments"]
        [::std::mem::offset_of!(rcl_node_options_s, use_global_arguments) - 40usize];
    ["Offset of field: rcl_node_options_s::arguments"]
        [::std::mem::offset_of!(rcl_node_options_s, arguments) - 48usize];
    ["Offset of field: rcl_node_options_s::enable_rosout"]
        [::std::mem::offset_of!(rcl_node_options_s, enable_rosout) - 56usize];
    ["Offset of field: rcl_node_options_s::rosout_qos"]
        [::std::mem::offset_of!(rcl_node_options_s, rosout_qos) - 64usize];
};
pub type rcl_node_options_t = rcl_node_options_s;
unsafe extern "C" {
    pub fn rcl_node_get_default_options() -> rcl_node_options_t;
}
unsafe extern "C" {
    pub fn rcl_node_options_fini(options: *mut rcl_node_options_t) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__String {
    pub data: *mut ::std::os::raw::c_char,
    pub size: usize,
    pub capacity: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__String"]
        [::std::mem::size_of::<rosidl_runtime_c__String>() - 24usize];
    ["Alignment of rosidl_runtime_c__String"]
        [::std::mem::align_of::<rosidl_runtime_c__String>() - 8usize];
    ["Offset of field: rosidl_runtime_c__String::data"]
        [::std::mem::offset_of!(rosidl_runtime_c__String, data) - 0usize];
    ["Offset of field: rosidl_runtime_c__String::size"]
        [::std::mem::offset_of!(rosidl_runtime_c__String, size) - 8usize];
    ["Offset of field: rosidl_runtime_c__String::capacity"]
        [::std::mem::offset_of!(rosidl_runtime_c__String, capacity) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__FieldType {
    pub type_id: u8,
    pub capacity: u64,
    pub string_capacity: u64,
    pub nested_type_name: rosidl_runtime_c__String,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__FieldType"]
        [::std::mem::size_of::<rosidl_runtime_c__type_description__FieldType>() - 48usize];
    ["Alignment of rosidl_runtime_c__type_description__FieldType"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__FieldType>() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__FieldType::type_id"]
        [::std::mem::offset_of!(rosidl_runtime_c__type_description__FieldType, type_id) - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__FieldType::capacity"]
        [::std::mem::offset_of!(rosidl_runtime_c__type_description__FieldType, capacity) - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__FieldType::string_capacity"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__FieldType,
        string_capacity
    )
        - 16usize];
    ["Offset of field: rosidl_runtime_c__type_description__FieldType::nested_type_name"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__FieldType,
        nested_type_name
    )
        - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__Field {
    pub name: rosidl_runtime_c__String,
    pub type_: rosidl_runtime_c__type_description__FieldType,
    pub default_value: rosidl_runtime_c__String,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__Field"]
        [::std::mem::size_of::<rosidl_runtime_c__type_description__Field>() - 96usize];
    ["Alignment of rosidl_runtime_c__type_description__Field"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__Field>() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field::name"]
        [::std::mem::offset_of!(rosidl_runtime_c__type_description__Field, name) - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field::type_"]
        [::std::mem::offset_of!(rosidl_runtime_c__type_description__Field, type_) - 24usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field::default_value"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__Field,
        default_value
    ) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__Field__Sequence {
    pub data: *mut rosidl_runtime_c__type_description__Field,
    pub size: usize,
    pub capacity: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__Field__Sequence"]
        [::std::mem::size_of::<rosidl_runtime_c__type_description__Field__Sequence>() - 24usize];
    ["Alignment of rosidl_runtime_c__type_description__Field__Sequence"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__Field__Sequence>() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field__Sequence::data"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__Field__Sequence,
        data
    ) - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field__Sequence::size"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__Field__Sequence,
        size
    ) - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__Field__Sequence::capacity"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__Field__Sequence,
        capacity
    ) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__IndividualTypeDescription {
    pub type_name: rosidl_runtime_c__String,
    pub fields: rosidl_runtime_c__type_description__Field__Sequence,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__IndividualTypeDescription"][::std::mem::size_of::<
        rosidl_runtime_c__type_description__IndividualTypeDescription,
    >() - 48usize];
    ["Alignment of rosidl_runtime_c__type_description__IndividualTypeDescription"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__IndividualTypeDescription>()
            - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__IndividualTypeDescription::type_name"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__IndividualTypeDescription,
        type_name
    )
        - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__IndividualTypeDescription::fields"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__IndividualTypeDescription,
        fields
    )
        - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence {
    pub data: *mut rosidl_runtime_c__type_description__IndividualTypeDescription,
    pub size: usize,
    pub capacity: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence"]
        [::std::mem::size_of::<
            rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
        >() - 24usize];
    ["Alignment of rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence"]
        [::std::mem::align_of::<
            rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
        >() - 8usize];
    [
        "Offset of field: rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence::data",
    ][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
        data
    ) - 0usize];
    [
        "Offset of field: rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence::size",
    ][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
        size
    ) - 8usize];
    [
        "Offset of field: rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence::capacity",
    ][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
        capacity
    ) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__TypeDescription {
    pub type_description: rosidl_runtime_c__type_description__IndividualTypeDescription,
    pub referenced_type_descriptions:
        rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__TypeDescription"]
        [::std::mem::size_of::<rosidl_runtime_c__type_description__TypeDescription>() - 72usize];
    ["Alignment of rosidl_runtime_c__type_description__TypeDescription"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__TypeDescription>() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeDescription::type_description"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeDescription,
        type_description
    )
        - 0usize];
    [
        "Offset of field: rosidl_runtime_c__type_description__TypeDescription::referenced_type_descriptions",
    ][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeDescription,
        referenced_type_descriptions
    ) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__TypeSource {
    pub type_name: rosidl_runtime_c__String,
    pub encoding: rosidl_runtime_c__String,
    pub raw_file_contents: rosidl_runtime_c__String,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__TypeSource"]
        [::std::mem::size_of::<rosidl_runtime_c__type_description__TypeSource>() - 72usize];
    ["Alignment of rosidl_runtime_c__type_description__TypeSource"]
        [::std::mem::align_of::<rosidl_runtime_c__type_description__TypeSource>() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource::type_name"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource,
        type_name
    ) - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource::encoding"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource,
        encoding
    ) - 24usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource::raw_file_contents"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource,
        raw_file_contents
    )
        - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_runtime_c__type_description__TypeSource__Sequence {
    pub data: *mut rosidl_runtime_c__type_description__TypeSource,
    pub size: usize,
    pub capacity: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_runtime_c__type_description__TypeSource__Sequence"][::std::mem::size_of::<
        rosidl_runtime_c__type_description__TypeSource__Sequence,
    >() - 24usize];
    ["Alignment of rosidl_runtime_c__type_description__TypeSource__Sequence"][::std::mem::align_of::<
        rosidl_runtime_c__type_description__TypeSource__Sequence,
    >() - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource__Sequence::data"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource__Sequence,
        data
    ) - 0usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource__Sequence::size"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource__Sequence,
        size
    ) - 8usize];
    ["Offset of field: rosidl_runtime_c__type_description__TypeSource__Sequence::capacity"][::std::mem::offset_of!(
        rosidl_runtime_c__type_description__TypeSource__Sequence,
        capacity
    )
        - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_type_hash_s {
    pub version: u8,
    pub value: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_type_hash_s"][::std::mem::size_of::<rosidl_type_hash_s>() - 33usize];
    ["Alignment of rosidl_type_hash_s"][::std::mem::align_of::<rosidl_type_hash_s>() - 1usize];
    ["Offset of field: rosidl_type_hash_s::version"]
        [::std::mem::offset_of!(rosidl_type_hash_s, version) - 0usize];
    ["Offset of field: rosidl_type_hash_s::value"]
        [::std::mem::offset_of!(rosidl_type_hash_s, value) - 1usize];
};
pub type rosidl_type_hash_t = rosidl_type_hash_s;
pub type rosidl_message_typesupport_handle_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_message_type_support_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const rosidl_message_type_support_t,
>;
pub type rosidl_message_get_type_hash_function = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const rosidl_message_type_support_t) -> *const rosidl_type_hash_t,
>;
pub type rosidl_message_get_type_description_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_message_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeDescription,
>;
pub type rosidl_message_get_type_description_sources_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_message_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeSource__Sequence,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_message_type_support_t {
    pub typesupport_identifier: *const ::std::os::raw::c_char,
    pub data: *const ::std::os::raw::c_void,
    pub func: rosidl_message_typesupport_handle_function,
    pub get_type_hash_func: rosidl_message_get_type_hash_function,
    pub get_type_description_func: rosidl_message_get_type_description_function,
    pub get_type_description_sources_func: rosidl_message_get_type_description_sources_function,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_message_type_support_t"]
        [::std::mem::size_of::<rosidl_message_type_support_t>() - 48usize];
    ["Alignment of rosidl_message_type_support_t"]
        [::std::mem::align_of::<rosidl_message_type_support_t>() - 8usize];
    ["Offset of field: rosidl_message_type_support_t::typesupport_identifier"]
        [::std::mem::offset_of!(rosidl_message_type_support_t, typesupport_identifier) - 0usize];
    ["Offset of field: rosidl_message_type_support_t::data"]
        [::std::mem::offset_of!(rosidl_message_type_support_t, data) - 8usize];
    ["Offset of field: rosidl_message_type_support_t::func"]
        [::std::mem::offset_of!(rosidl_message_type_support_t, func) - 16usize];
    ["Offset of field: rosidl_message_type_support_t::get_type_hash_func"]
        [::std::mem::offset_of!(rosidl_message_type_support_t, get_type_hash_func) - 24usize];
    ["Offset of field: rosidl_message_type_support_t::get_type_description_func"][::std::mem::offset_of!(
        rosidl_message_type_support_t,
        get_type_description_func
    ) - 32usize];
    ["Offset of field: rosidl_message_type_support_t::get_type_description_sources_func"][::std::mem::offset_of!(
        rosidl_message_type_support_t,
        get_type_description_sources_func
    )
        - 40usize];
};
pub type rosidl_service_typesupport_handle_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_service_type_support_t,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const rosidl_service_type_support_t,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_service_introspection_info_s {
    pub event_type: u8,
    pub stamp_sec: i32,
    pub stamp_nanosec: u32,
    pub client_gid: [u8; 16usize],
    pub sequence_number: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_service_introspection_info_s"]
        [::std::mem::size_of::<rosidl_service_introspection_info_s>() - 40usize];
    ["Alignment of rosidl_service_introspection_info_s"]
        [::std::mem::align_of::<rosidl_service_introspection_info_s>() - 8usize];
    ["Offset of field: rosidl_service_introspection_info_s::event_type"]
        [::std::mem::offset_of!(rosidl_service_introspection_info_s, event_type) - 0usize];
    ["Offset of field: rosidl_service_introspection_info_s::stamp_sec"]
        [::std::mem::offset_of!(rosidl_service_introspection_info_s, stamp_sec) - 4usize];
    ["Offset of field: rosidl_service_introspection_info_s::stamp_nanosec"]
        [::std::mem::offset_of!(rosidl_service_introspection_info_s, stamp_nanosec) - 8usize];
    ["Offset of field: rosidl_service_introspection_info_s::client_gid"]
        [::std::mem::offset_of!(rosidl_service_introspection_info_s, client_gid) - 12usize];
    ["Offset of field: rosidl_service_introspection_info_s::sequence_number"]
        [::std::mem::offset_of!(rosidl_service_introspection_info_s, sequence_number) - 32usize];
};
pub type rosidl_service_introspection_info_t = rosidl_service_introspection_info_s;
pub type rosidl_event_message_create_handle_function_function = ::std::option::Option<
    unsafe extern "C" fn(
        info: *const rosidl_service_introspection_info_t,
        allocator: *mut rcutils_allocator_t,
        request_message: *const ::std::os::raw::c_void,
        response_message: *const ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type rosidl_event_message_destroy_handle_function_function = ::std::option::Option<
    unsafe extern "C" fn(
        event_message: *mut ::std::os::raw::c_void,
        allocator: *mut rcutils_allocator_t,
    ) -> bool,
>;
pub type rosidl_service_get_type_hash_function = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const rosidl_service_type_support_t) -> *const rosidl_type_hash_t,
>;
pub type rosidl_service_get_type_description_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_service_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeDescription,
>;
pub type rosidl_service_get_type_description_sources_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_service_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeSource__Sequence,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_service_type_support_t {
    pub typesupport_identifier: *const ::std::os::raw::c_char,
    pub data: *const ::std::os::raw::c_void,
    pub func: rosidl_service_typesupport_handle_function,
    pub request_typesupport: *const rosidl_message_type_support_t,
    pub response_typesupport: *const rosidl_message_type_support_t,
    pub event_typesupport: *const rosidl_message_type_support_t,
    pub event_message_create_handle_function: rosidl_event_message_create_handle_function_function,
    pub event_message_destroy_handle_function:
        rosidl_event_message_destroy_handle_function_function,
    pub get_type_hash_func: rosidl_service_get_type_hash_function,
    pub get_type_description_func: rosidl_service_get_type_description_function,
    pub get_type_description_sources_func: rosidl_service_get_type_description_sources_function,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_service_type_support_t"]
        [::std::mem::size_of::<rosidl_service_type_support_t>() - 88usize];
    ["Alignment of rosidl_service_type_support_t"]
        [::std::mem::align_of::<rosidl_service_type_support_t>() - 8usize];
    ["Offset of field: rosidl_service_type_support_t::typesupport_identifier"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, typesupport_identifier) - 0usize];
    ["Offset of field: rosidl_service_type_support_t::data"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, data) - 8usize];
    ["Offset of field: rosidl_service_type_support_t::func"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, func) - 16usize];
    ["Offset of field: rosidl_service_type_support_t::request_typesupport"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, request_typesupport) - 24usize];
    ["Offset of field: rosidl_service_type_support_t::response_typesupport"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, response_typesupport) - 32usize];
    ["Offset of field: rosidl_service_type_support_t::event_typesupport"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, event_typesupport) - 40usize];
    ["Offset of field: rosidl_service_type_support_t::event_message_create_handle_function"][::std::mem::offset_of!(
        rosidl_service_type_support_t,
        event_message_create_handle_function
    )
        - 48usize];
    ["Offset of field: rosidl_service_type_support_t::event_message_destroy_handle_function"][::std::mem::offset_of!(
        rosidl_service_type_support_t,
        event_message_destroy_handle_function
    )
        - 56usize];
    ["Offset of field: rosidl_service_type_support_t::get_type_hash_func"]
        [::std::mem::offset_of!(rosidl_service_type_support_t, get_type_hash_func) - 64usize];
    ["Offset of field: rosidl_service_type_support_t::get_type_description_func"][::std::mem::offset_of!(
        rosidl_service_type_support_t,
        get_type_description_func
    ) - 72usize];
    ["Offset of field: rosidl_service_type_support_t::get_type_description_sources_func"][::std::mem::offset_of!(
        rosidl_service_type_support_t,
        get_type_description_sources_func
    )
        - 80usize];
};
pub type rosidl_action_get_type_hash_function = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const rosidl_action_type_support_t) -> *const rosidl_type_hash_t,
>;
pub type rosidl_action_get_type_description_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_action_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeDescription,
>;
pub type rosidl_action_get_type_description_sources_function = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const rosidl_action_type_support_t,
    ) -> *const rosidl_runtime_c__type_description__TypeSource__Sequence,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rosidl_action_type_support_t {
    pub goal_service_type_support: *const rosidl_service_type_support_t,
    pub result_service_type_support: *const rosidl_service_type_support_t,
    pub cancel_service_type_support: *const rosidl_service_type_support_t,
    pub feedback_message_type_support: *const rosidl_message_type_support_t,
    pub status_message_type_support: *const rosidl_message_type_support_t,
    pub get_type_hash_func: rosidl_action_get_type_hash_function,
    pub get_type_description_func: rosidl_action_get_type_description_function,
    pub get_type_description_sources_func: rosidl_action_get_type_description_sources_function,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rosidl_action_type_support_t"]
        [::std::mem::size_of::<rosidl_action_type_support_t>() - 64usize];
    ["Alignment of rosidl_action_type_support_t"]
        [::std::mem::align_of::<rosidl_action_type_support_t>() - 8usize];
    ["Offset of field: rosidl_action_type_support_t::goal_service_type_support"]
        [::std::mem::offset_of!(rosidl_action_type_support_t, goal_service_type_support) - 0usize];
    ["Offset of field: rosidl_action_type_support_t::result_service_type_support"][::std::mem::offset_of!(
        rosidl_action_type_support_t,
        result_service_type_support
    ) - 8usize];
    ["Offset of field: rosidl_action_type_support_t::cancel_service_type_support"][::std::mem::offset_of!(
        rosidl_action_type_support_t,
        cancel_service_type_support
    ) - 16usize];
    ["Offset of field: rosidl_action_type_support_t::feedback_message_type_support"][::std::mem::offset_of!(
        rosidl_action_type_support_t,
        feedback_message_type_support
    ) - 24usize];
    ["Offset of field: rosidl_action_type_support_t::status_message_type_support"][::std::mem::offset_of!(
        rosidl_action_type_support_t,
        status_message_type_support
    ) - 32usize];
    ["Offset of field: rosidl_action_type_support_t::get_type_hash_func"]
        [::std::mem::offset_of!(rosidl_action_type_support_t, get_type_hash_func) - 40usize];
    ["Offset of field: rosidl_action_type_support_t::get_type_description_func"]
        [::std::mem::offset_of!(rosidl_action_type_support_t, get_type_description_func) - 48usize];
    ["Offset of field: rosidl_action_type_support_t::get_type_description_sources_func"][::std::mem::offset_of!(
        rosidl_action_type_support_t,
        get_type_description_sources_func
    )
        - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_node_impl_s {
    _unused: [u8; 0],
}
pub type rcl_node_impl_t = rcl_node_impl_s;
pub type rcl_service_t = rcl_service_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_node_s {
    pub context: *mut rcl_context_t,
    pub impl_: *mut rcl_node_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_node_s"][::std::mem::size_of::<rcl_node_s>() - 16usize];
    ["Alignment of rcl_node_s"][::std::mem::align_of::<rcl_node_s>() - 8usize];
    ["Offset of field: rcl_node_s::context"][::std::mem::offset_of!(rcl_node_s, context) - 0usize];
    ["Offset of field: rcl_node_s::impl_"][::std::mem::offset_of!(rcl_node_s, impl_) - 8usize];
};
pub type rcl_node_t = rcl_node_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_node() -> rcl_node_t;
}
unsafe extern "C" {
    pub fn rcl_node_init(
        node: *mut rcl_node_t,
        name: *const ::std::os::raw::c_char,
        namespace_: *const ::std::os::raw::c_char,
        context: *mut rcl_context_t,
        options: *const rcl_node_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_node_fini(node: *mut rcl_node_t) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_publisher_impl_s {
    _unused: [u8; 0],
}
pub type rcl_publisher_impl_t = rcl_publisher_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_publisher_s {
    pub impl_: *mut rcl_publisher_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_publisher_s"][::std::mem::size_of::<rcl_publisher_s>() - 8usize];
    ["Alignment of rcl_publisher_s"][::std::mem::align_of::<rcl_publisher_s>() - 8usize];
    ["Offset of field: rcl_publisher_s::impl_"]
        [::std::mem::offset_of!(rcl_publisher_s, impl_) - 0usize];
};
pub type rcl_publisher_t = rcl_publisher_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_publisher_options_s {
    pub qos: rmw_qos_profile_t,
    pub allocator: rcl_allocator_t,
    pub rmw_publisher_options: rmw_publisher_options_t,
    pub disable_loaned_message: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_publisher_options_s"]
        [::std::mem::size_of::<rcl_publisher_options_s>() - 152usize];
    ["Alignment of rcl_publisher_options_s"]
        [::std::mem::align_of::<rcl_publisher_options_s>() - 8usize];
    ["Offset of field: rcl_publisher_options_s::qos"]
        [::std::mem::offset_of!(rcl_publisher_options_s, qos) - 0usize];
    ["Offset of field: rcl_publisher_options_s::allocator"]
        [::std::mem::offset_of!(rcl_publisher_options_s, allocator) - 88usize];
    ["Offset of field: rcl_publisher_options_s::rmw_publisher_options"]
        [::std::mem::offset_of!(rcl_publisher_options_s, rmw_publisher_options) - 128usize];
    ["Offset of field: rcl_publisher_options_s::disable_loaned_message"]
        [::std::mem::offset_of!(rcl_publisher_options_s, disable_loaned_message) - 144usize];
};
pub type rcl_publisher_options_t = rcl_publisher_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_publisher() -> rcl_publisher_t;
}
unsafe extern "C" {
    pub fn rcl_publisher_init(
        publisher: *mut rcl_publisher_t,
        node: *const rcl_node_t,
        type_support: *const rosidl_message_type_support_t,
        topic_name: *const ::std::os::raw::c_char,
        options: *const rcl_publisher_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_publisher_fini(publisher: *mut rcl_publisher_t, node: *mut rcl_node_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_publisher_get_default_options() -> rcl_publisher_options_t;
}
unsafe extern "C" {
    pub fn rcl_publish_serialized_message(
        publisher: *const rcl_publisher_t,
        serialized_message: *const rcl_serialized_message_t,
        allocation: *mut rmw_publisher_allocation_t,
    ) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_subscription_impl_s {
    _unused: [u8; 0],
}
pub type rcl_subscription_impl_t = rcl_subscription_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_subscription_s {
    pub impl_: *mut rcl_subscription_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_subscription_s"][::std::mem::size_of::<rcl_subscription_s>() - 8usize];
    ["Alignment of rcl_subscription_s"][::std::mem::align_of::<rcl_subscription_s>() - 8usize];
    ["Offset of field: rcl_subscription_s::impl_"]
        [::std::mem::offset_of!(rcl_subscription_s, impl_) - 0usize];
};
pub type rcl_subscription_t = rcl_subscription_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_subscription_options_s {
    pub qos: rmw_qos_profile_t,
    pub allocator: rcl_allocator_t,
    pub rmw_subscription_options: rmw_subscription_options_t,
    pub disable_loaned_message: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_subscription_options_s"]
        [::std::mem::size_of::<rcl_subscription_options_s>() - 160usize];
    ["Alignment of rcl_subscription_options_s"]
        [::std::mem::align_of::<rcl_subscription_options_s>() - 8usize];
    ["Offset of field: rcl_subscription_options_s::qos"]
        [::std::mem::offset_of!(rcl_subscription_options_s, qos) - 0usize];
    ["Offset of field: rcl_subscription_options_s::allocator"]
        [::std::mem::offset_of!(rcl_subscription_options_s, allocator) - 88usize];
    ["Offset of field: rcl_subscription_options_s::rmw_subscription_options"]
        [::std::mem::offset_of!(rcl_subscription_options_s, rmw_subscription_options) - 128usize];
    ["Offset of field: rcl_subscription_options_s::disable_loaned_message"]
        [::std::mem::offset_of!(rcl_subscription_options_s, disable_loaned_message) - 152usize];
};
pub type rcl_subscription_options_t = rcl_subscription_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_subscription() -> rcl_subscription_t;
}
unsafe extern "C" {
    pub fn rcl_subscription_init(
        subscription: *mut rcl_subscription_t,
        node: *const rcl_node_t,
        type_support: *const rosidl_message_type_support_t,
        topic_name: *const ::std::os::raw::c_char,
        options: *const rcl_subscription_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_subscription_fini(
        subscription: *mut rcl_subscription_t,
        node: *mut rcl_node_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_subscription_get_default_options() -> rcl_subscription_options_t;
}
unsafe extern "C" {
    pub fn rcl_take_serialized_message(
        subscription: *const rcl_subscription_t,
        serialized_message: *mut rcl_serialized_message_t,
        message_info: *mut rmw_message_info_t,
        allocation: *mut rmw_subscription_allocation_t,
    ) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_client_impl_s {
    _unused: [u8; 0],
}
pub type rcl_client_impl_t = rcl_client_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_client_s {
    pub impl_: *mut rcl_client_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_client_s"][::std::mem::size_of::<rcl_client_s>() - 8usize];
    ["Alignment of rcl_client_s"][::std::mem::align_of::<rcl_client_s>() - 8usize];
    ["Offset of field: rcl_client_s::impl_"][::std::mem::offset_of!(rcl_client_s, impl_) - 0usize];
};
pub type rcl_client_t = rcl_client_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_client_options_s {
    pub qos: rmw_qos_profile_t,
    pub allocator: rcl_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_client_options_s"][::std::mem::size_of::<rcl_client_options_s>() - 128usize];
    ["Alignment of rcl_client_options_s"][::std::mem::align_of::<rcl_client_options_s>() - 8usize];
    ["Offset of field: rcl_client_options_s::qos"]
        [::std::mem::offset_of!(rcl_client_options_s, qos) - 0usize];
    ["Offset of field: rcl_client_options_s::allocator"]
        [::std::mem::offset_of!(rcl_client_options_s, allocator) - 88usize];
};
pub type rcl_client_options_t = rcl_client_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_client() -> rcl_client_t;
}
unsafe extern "C" {
    pub fn rcl_client_init(
        client: *mut rcl_client_t,
        node: *const rcl_node_t,
        type_support: *const rosidl_service_type_support_t,
        service_name: *const ::std::os::raw::c_char,
        options: *const rcl_client_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_client_fini(client: *mut rcl_client_t, node: *mut rcl_node_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_client_get_default_options() -> rcl_client_options_t;
}
unsafe extern "C" {
    pub fn rcl_send_request(
        client: *const rcl_client_t,
        ros_request: *const ::std::os::raw::c_void,
        sequence_number: *mut i64,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_take_response_with_info(
        client: *const rcl_client_t,
        request_header: *mut rmw_service_info_t,
        ros_response: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_take_response(
        client: *const rcl_client_t,
        request_header: *mut rmw_request_id_t,
        ros_response: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_service_impl_s {
    _unused: [u8; 0],
}
pub type rcl_service_impl_t = rcl_service_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_service_s {
    pub impl_: *mut rcl_service_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_service_s"][::std::mem::size_of::<rcl_service_s>() - 8usize];
    ["Alignment of rcl_service_s"][::std::mem::align_of::<rcl_service_s>() - 8usize];
    ["Offset of field: rcl_service_s::impl_"]
        [::std::mem::offset_of!(rcl_service_s, impl_) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_service_options_s {
    pub qos: rmw_qos_profile_t,
    pub allocator: rcl_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_service_options_s"][::std::mem::size_of::<rcl_service_options_s>() - 128usize];
    ["Alignment of rcl_service_options_s"]
        [::std::mem::align_of::<rcl_service_options_s>() - 8usize];
    ["Offset of field: rcl_service_options_s::qos"]
        [::std::mem::offset_of!(rcl_service_options_s, qos) - 0usize];
    ["Offset of field: rcl_service_options_s::allocator"]
        [::std::mem::offset_of!(rcl_service_options_s, allocator) - 88usize];
};
pub type rcl_service_options_t = rcl_service_options_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_service() -> rcl_service_t;
}
unsafe extern "C" {
    pub fn rcl_service_init(
        service: *mut rcl_service_t,
        node: *const rcl_node_t,
        type_support: *const rosidl_service_type_support_t,
        service_name: *const ::std::os::raw::c_char,
        options: *const rcl_service_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_service_fini(service: *mut rcl_service_t, node: *mut rcl_node_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_service_get_default_options() -> rcl_service_options_t;
}
unsafe extern "C" {
    pub fn rcl_take_request_with_info(
        service: *const rcl_service_t,
        request_header: *mut rmw_service_info_t,
        ros_request: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_take_request(
        service: *const rcl_service_t,
        request_header: *mut rmw_request_id_t,
        ros_request: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_send_response(
        service: *const rcl_service_t,
        response_header: *mut rmw_request_id_t,
        ros_response: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rmw_serialize(
        ros_message: *const ::std::os::raw::c_void,
        type_support: *const rosidl_message_type_support_t,
        serialized_message: *mut rmw_serialized_message_t,
    ) -> rmw_ret_t;
}
unsafe extern "C" {
    pub fn rmw_deserialize(
        serialized_message: *const rmw_serialized_message_t,
        type_support: *const rosidl_message_type_support_t,
        ros_message: *mut ::std::os::raw::c_void,
    ) -> rmw_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_timer_impl_s {
    _unused: [u8; 0],
}
pub type rcl_timer_impl_t = rcl_timer_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_timer_s {
    pub impl_: *mut rcl_timer_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_timer_s"][::std::mem::size_of::<rcl_timer_s>() - 8usize];
    ["Alignment of rcl_timer_s"][::std::mem::align_of::<rcl_timer_s>() - 8usize];
    ["Offset of field: rcl_timer_s::impl_"][::std::mem::offset_of!(rcl_timer_s, impl_) - 0usize];
};
pub type rcl_timer_t = rcl_timer_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_event_impl_s {
    _unused: [u8; 0],
}
pub type rcl_event_impl_t = rcl_event_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_event_s {
    pub impl_: *mut rcl_event_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_event_s"][::std::mem::size_of::<rcl_event_s>() - 8usize];
    ["Alignment of rcl_event_s"][::std::mem::align_of::<rcl_event_s>() - 8usize];
    ["Offset of field: rcl_event_s::impl_"][::std::mem::offset_of!(rcl_event_s, impl_) - 0usize];
};
pub type rcl_event_t = rcl_event_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_wait_set_impl_s {
    _unused: [u8; 0],
}
pub type rcl_wait_set_impl_t = rcl_wait_set_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_wait_set_s {
    pub subscriptions: *mut *const rcl_subscription_t,
    pub size_of_subscriptions: usize,
    pub guard_conditions: *mut *const rcl_guard_condition_t,
    pub size_of_guard_conditions: usize,
    pub timers: *mut *const rcl_timer_t,
    pub size_of_timers: usize,
    pub clients: *mut *const rcl_client_t,
    pub size_of_clients: usize,
    pub services: *mut *const rcl_service_t,
    pub size_of_services: usize,
    pub events: *mut *const rcl_event_t,
    pub size_of_events: usize,
    pub impl_: *mut rcl_wait_set_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_wait_set_s"][::std::mem::size_of::<rcl_wait_set_s>() - 104usize];
    ["Alignment of rcl_wait_set_s"][::std::mem::align_of::<rcl_wait_set_s>() - 8usize];
    ["Offset of field: rcl_wait_set_s::subscriptions"]
        [::std::mem::offset_of!(rcl_wait_set_s, subscriptions) - 0usize];
    ["Offset of field: rcl_wait_set_s::size_of_subscriptions"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_subscriptions) - 8usize];
    ["Offset of field: rcl_wait_set_s::guard_conditions"]
        [::std::mem::offset_of!(rcl_wait_set_s, guard_conditions) - 16usize];
    ["Offset of field: rcl_wait_set_s::size_of_guard_conditions"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_guard_conditions) - 24usize];
    ["Offset of field: rcl_wait_set_s::timers"]
        [::std::mem::offset_of!(rcl_wait_set_s, timers) - 32usize];
    ["Offset of field: rcl_wait_set_s::size_of_timers"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_timers) - 40usize];
    ["Offset of field: rcl_wait_set_s::clients"]
        [::std::mem::offset_of!(rcl_wait_set_s, clients) - 48usize];
    ["Offset of field: rcl_wait_set_s::size_of_clients"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_clients) - 56usize];
    ["Offset of field: rcl_wait_set_s::services"]
        [::std::mem::offset_of!(rcl_wait_set_s, services) - 64usize];
    ["Offset of field: rcl_wait_set_s::size_of_services"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_services) - 72usize];
    ["Offset of field: rcl_wait_set_s::events"]
        [::std::mem::offset_of!(rcl_wait_set_s, events) - 80usize];
    ["Offset of field: rcl_wait_set_s::size_of_events"]
        [::std::mem::offset_of!(rcl_wait_set_s, size_of_events) - 88usize];
    ["Offset of field: rcl_wait_set_s::impl_"]
        [::std::mem::offset_of!(rcl_wait_set_s, impl_) - 96usize];
};
pub type rcl_wait_set_t = rcl_wait_set_s;
unsafe extern "C" {
    pub fn rcl_get_zero_initialized_wait_set() -> rcl_wait_set_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_init(
        wait_set: *mut rcl_wait_set_t,
        number_of_subscriptions: usize,
        number_of_guard_conditions: usize,
        number_of_timers: usize,
        number_of_clients: usize,
        number_of_services: usize,
        number_of_events: usize,
        context: *mut rcl_context_t,
        allocator: rcl_allocator_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_fini(wait_set: *mut rcl_wait_set_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_add_subscription(
        wait_set: *mut rcl_wait_set_t,
        subscription: *const rcl_subscription_t,
        index: *mut usize,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_clear(wait_set: *mut rcl_wait_set_t) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_add_guard_condition(
        wait_set: *mut rcl_wait_set_t,
        guard_condition: *const rcl_guard_condition_t,
        index: *mut usize,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_add_client(
        wait_set: *mut rcl_wait_set_t,
        client: *const rcl_client_t,
        index: *mut usize,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait_set_add_service(
        wait_set: *mut rcl_wait_set_t,
        service: *const rcl_service_t,
        index: *mut usize,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_wait(wait_set: *mut rcl_wait_set_t, timeout: i64) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rmw_names_and_types_s {
    pub names: rcutils_string_array_t,
    pub types: *mut rcutils_string_array_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rmw_names_and_types_s"][::std::mem::size_of::<rmw_names_and_types_s>() - 64usize];
    ["Alignment of rmw_names_and_types_s"]
        [::std::mem::align_of::<rmw_names_and_types_s>() - 8usize];
    ["Offset of field: rmw_names_and_types_s::names"]
        [::std::mem::offset_of!(rmw_names_and_types_s, names) - 0usize];
    ["Offset of field: rmw_names_and_types_s::types"]
        [::std::mem::offset_of!(rmw_names_and_types_s, types) - 56usize];
};
pub type rmw_names_and_types_t = rmw_names_and_types_s;
unsafe extern "C" {
    pub fn rmw_get_zero_initialized_names_and_types() -> rmw_names_and_types_t;
}
pub type rcl_names_and_types_t = rmw_names_and_types_t;
unsafe extern "C" {
    pub fn rcl_get_topic_names_and_types(
        node: *const rcl_node_t,
        allocator: *mut rcl_allocator_t,
        no_demangle: bool,
        topic_names_and_types: *mut rcl_names_and_types_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_get_service_names_and_types(
        node: *const rcl_node_t,
        allocator: *mut rcl_allocator_t,
        service_names_and_types: *mut rcl_names_and_types_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_names_and_types_fini(names_and_types: *mut rcl_names_and_types_t) -> rcl_ret_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_action_client_impl_s {
    _unused: [u8; 0],
}
pub type rcl_action_client_impl_t = rcl_action_client_impl_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_action_client_s {
    pub impl_: *mut rcl_action_client_impl_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_action_client_s"][::std::mem::size_of::<rcl_action_client_s>() - 8usize];
    ["Alignment of rcl_action_client_s"][::std::mem::align_of::<rcl_action_client_s>() - 8usize];
    ["Offset of field: rcl_action_client_s::impl_"]
        [::std::mem::offset_of!(rcl_action_client_s, impl_) - 0usize];
};
pub type rcl_action_client_t = rcl_action_client_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rcl_action_client_options_s {
    pub goal_service_qos: rmw_qos_profile_t,
    pub result_service_qos: rmw_qos_profile_t,
    pub cancel_service_qos: rmw_qos_profile_t,
    pub feedback_topic_qos: rmw_qos_profile_t,
    pub status_topic_qos: rmw_qos_profile_t,
    pub allocator: rcl_allocator_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rcl_action_client_options_s"]
        [::std::mem::size_of::<rcl_action_client_options_s>() - 480usize];
    ["Alignment of rcl_action_client_options_s"]
        [::std::mem::align_of::<rcl_action_client_options_s>() - 8usize];
    ["Offset of field: rcl_action_client_options_s::goal_service_qos"]
        [::std::mem::offset_of!(rcl_action_client_options_s, goal_service_qos) - 0usize];
    ["Offset of field: rcl_action_client_options_s::result_service_qos"]
        [::std::mem::offset_of!(rcl_action_client_options_s, result_service_qos) - 88usize];
    ["Offset of field: rcl_action_client_options_s::cancel_service_qos"]
        [::std::mem::offset_of!(rcl_action_client_options_s, cancel_service_qos) - 176usize];
    ["Offset of field: rcl_action_client_options_s::feedback_topic_qos"]
        [::std::mem::offset_of!(rcl_action_client_options_s, feedback_topic_qos) - 264usize];
    ["Offset of field: rcl_action_client_options_s::status_topic_qos"]
        [::std::mem::offset_of!(rcl_action_client_options_s, status_topic_qos) - 352usize];
    ["Offset of field: rcl_action_client_options_s::allocator"]
        [::std::mem::offset_of!(rcl_action_client_options_s, allocator) - 440usize];
};
pub type rcl_action_client_options_t = rcl_action_client_options_s;
unsafe extern "C" {
    pub fn rcl_action_get_zero_initialized_client() -> rcl_action_client_t;
}
unsafe extern "C" {
    pub fn rcl_action_client_init(
        action_client: *mut rcl_action_client_t,
        node: *mut rcl_node_t,
        type_support: *const rosidl_action_type_support_t,
        action_name: *const ::std::os::raw::c_char,
        options: *const rcl_action_client_options_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_client_fini(
        action_client: *mut rcl_action_client_t,
        node: *mut rcl_node_t,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_client_get_default_options() -> rcl_action_client_options_t;
}
unsafe extern "C" {
    pub fn rcl_action_server_is_available(
        node: *const rcl_node_t,
        client: *const rcl_action_client_t,
        is_available: *mut bool,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_send_goal_request(
        action_client: *const rcl_action_client_t,
        ros_goal_request: *const ::std::os::raw::c_void,
        sequence_number: *mut i64,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_take_goal_response(
        action_client: *const rcl_action_client_t,
        response_header: *mut rmw_request_id_t,
        ros_goal_response: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_send_result_request(
        action_client: *const rcl_action_client_t,
        ros_result_request: *const ::std::os::raw::c_void,
        sequence_number: *mut i64,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_take_result_response(
        action_client: *const rcl_action_client_t,
        response_header: *mut rmw_request_id_t,
        ros_result: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_send_cancel_request(
        action_client: *const rcl_action_client_t,
        ros_cancel_request: *const ::std::os::raw::c_void,
        sequence_number: *mut i64,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_take_cancel_response(
        action_client: *const rcl_action_client_t,
        response_header: *mut rmw_request_id_t,
        ros_cancel_response: *mut ::std::os::raw::c_void,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_wait_set_add_action_client(
        wait_set: *mut rcl_wait_set_t,
        action_client: *const rcl_action_client_t,
        client_index: *mut usize,
        subscription_index: *mut usize,
    ) -> rcl_ret_t;
}
unsafe extern "C" {
    pub fn rcl_action_client_wait_set_get_num_entities(
        action_client: *const rcl_action_client_t,
        num_subscriptions: *mut usize,
        num_guard_conditions: *mut usize,
        num_timers: *mut usize,
        num_clients: *mut usize,
        num_services: *mut usize,
    ) -> rcl_ret_t;
}
