import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import {
  installedPackageManifest,
  licenseDiagnostics,
  licenseExpressionAllowed,
  modelFromBunWorkspace,
  normalizeLicenseExpression,
  renderInventoryMarkdown,
  splitTopLevel,
} from "./license-inventory.ts";

describe("licenseExpressionAllowed", () => {
  test("accepts allowlisted identifiers and WITH exceptions", () => {
    expect(licenseExpressionAllowed("MIT")).toBe(true);
    expect(licenseExpressionAllowed("Apache-2.0")).toBe(true);
    expect(licenseExpressionAllowed("Apache-2.0 WITH LLVM-exception")).toBe(true);
    expect(licenseExpressionAllowed("Unicode-3.0")).toBe(true);
  });

  test("accepts OR when any alternative is allowed", () => {
    expect(licenseExpressionAllowed("MIT OR Apache-2.0")).toBe(true);
    expect(licenseExpressionAllowed("GPL-3.0-only OR MIT")).toBe(true);
    expect(licenseExpressionAllowed("MIT/Apache-2.0")).toBe(true);
  });

  test("accepts AND only when every part is allowed", () => {
    expect(licenseExpressionAllowed("MIT AND ISC AND OpenSSL")).toBe(true);
    expect(licenseExpressionAllowed("(Apache-2.0 OR MIT) AND Unicode-3.0")).toBe(true);
    expect(licenseExpressionAllowed("MIT AND GPL-3.0-only")).toBe(false);
  });

  test("rejects copyleft, empty, and unknown expressions", () => {
    expect(licenseExpressionAllowed("GPL-3.0-only")).toBe(false);
    expect(licenseExpressionAllowed("AGPL-3.0-only")).toBe(false);
    expect(licenseExpressionAllowed("LGPL-2.1-or-later")).toBe(false);
    expect(licenseExpressionAllowed("MPL-2.0")).toBe(false);
    expect(licenseExpressionAllowed("")).toBe(false);
    expect(licenseExpressionAllowed("   ")).toBe(false);
    expect(licenseExpressionAllowed(null)).toBe(false);
    expect(licenseExpressionAllowed("license-file:LICENSE")).toBe(false);
  });
});

describe("normalizeLicenseExpression", () => {
  test("rewrites legacy cargo slash form", () => {
    expect(normalizeLicenseExpression("MIT/Apache-2.0")).toBe("MIT OR Apache-2.0");
    expect(normalizeLicenseExpression("MIT / Apache-2.0")).toBe("MIT OR Apache-2.0");
  });
});

describe("splitTopLevel", () => {
  test("does not split inside parentheses", () => {
    expect(splitTopLevel("(Apache-2.0 OR MIT) AND Unicode-3.0", "AND")).toEqual([
      "(Apache-2.0 OR MIT)",
      "Unicode-3.0",
    ]);
    expect(splitTopLevel("(Apache-2.0 OR MIT) AND Unicode-3.0", "OR")).toEqual([
      "(Apache-2.0 OR MIT) AND Unicode-3.0",
    ]);
  });
});

describe("licenseDiagnostics", () => {
  test("names the offending crate", () => {
    expect(
      licenseDiagnostics([
        { name: "ok", version: "1.0.0", license: "MIT" },
        { name: "bad", version: "2.0.0", license: "GPL-3.0-only" },
      ]),
    ).toEqual(['bad@2.0.0: disallowed or missing license "GPL-3.0-only"']);
  });
});

describe("renderInventoryMarkdown", () => {
  test("is deterministic and enrolls licensing links", () => {
    const text = renderInventoryMarkdown({
      published: [
        { name: "bytes", version: "1.0.0", license: "MIT" },
        { name: "axum", version: "0.8.0", license: "MIT" },
      ],
      development: [{ name: "tokio-tungstenite", version: "0.30.0", license: "MIT" }],
      bunExternal: [],
      bunWorkspace: ["rclweb", "@rclweb/e2e-harness"],
    });
    expect(text.startsWith("<!-- Generated by `just license-inventory`.")).toBe(true);
    expect(text).toContain("| axum | 0.8.0 | MIT |");
    expect(text).toContain("| bytes | 1.0.0 | MIT |");
    expect(text.indexOf("| axum |")).toBeLessThan(text.indexOf("| bytes |"));
    expect(text).toContain("[licensing](./licensing.md)");
    expect(text).toContain("No external npm dependencies");
    expect(text.endsWith("\n")).toBe(true);
  });
});

describe("installedPackageManifest", () => {
  test("prefers the declaring workspace node_modules over a missing root hoist", () => {
    const root = mkdtempSync(path.join(tmpdir(), "rclweb-license-"));
    const nested = path.join(root, "typescript", "node_modules", "tsdown", "package.json");
    mkdirSync(path.dirname(nested), { recursive: true });
    writeFileSync(nested, JSON.stringify({ name: "tsdown", version: "0.22.14", license: "MIT" }));
    expect(installedPackageManifest(root, "typescript", "tsdown")).toBe(nested);
    expect(installedPackageManifest(root, ".", "tsdown")).toBeUndefined();
  });

  test("reads a scoped package under node_modules/@scope/name", () => {
    const root = mkdtempSync(path.join(tmpdir(), "rclweb-license-scope-"));
    const nested = path.join(root, "node_modules", "@foo", "bar", "package.json");
    mkdirSync(path.dirname(nested), { recursive: true });
    writeFileSync(nested, "{}");
    expect(installedPackageManifest(root, ".", "@foo/bar")).toBe(nested);
  });
});

describe("modelFromBunWorkspace", () => {
  test("reads license from a workspace-nested install", () => {
    const root = mkdtempSync(path.join(tmpdir(), "rclweb-license-ws-"));
    writeFileSync(
      path.join(root, "package.json"),
      JSON.stringify({ name: "root", private: true, workspaces: ["pkg"] }),
    );
    mkdirSync(path.join(root, "pkg"));
    writeFileSync(
      path.join(root, "pkg", "package.json"),
      JSON.stringify({ name: "pkg", devDependencies: { tsdown: "0.22.14" } }),
    );
    const nested = path.join(root, "pkg", "node_modules", "tsdown", "package.json");
    mkdirSync(path.dirname(nested), { recursive: true });
    writeFileSync(nested, JSON.stringify({ name: "tsdown", version: "0.22.14", license: "MIT" }));
    expect(modelFromBunWorkspace(root)).toEqual({
      bunWorkspace: ["root", "pkg"],
      bunExternal: [{ name: "tsdown", version: "0.22.14", license: "MIT" }],
    });
  });
});
